### ISSUE TITLE
Cannot read property 'children' of null

### ISSUE THREAD

**Issue by mateuszf** [JamesMGreene/qunit-composite#12]
Tested with qunit-composite 1.0.2 and current master with QUnit 1.13.0 and 1.16.0

I'm running simplest test case as defined at http://qunitjs.com/ in "A minimal QUnit test setup:"

I also created simplest possible page which basically loads "qunit.css", "qunit-composite.css", "qunit.js", "qunit-composite.js" and executes only:
```javascript
QUnit.testSuites(["test1.html"]);
```
I get following errors:
Chrome 39 (with --allow-file-access-from-files): "Uncaught TypeError: Cannot read property 'children' of null"
Firefox 33.1.1: "TypeError: current is null"
IE 11: "Unable to get property 'children' of undefined or null reference"

What am I doing wrong ?

**Comment by JamesMGreene** [comment]
Fixed in `v1.0.4`.

**Comment by JamesMGreene** [comment]
P.S. I gave it a quick test and it worked for me with QUnit for _at least_ versions `v1.10.0` through `v1.16.0`.

**Comment by mateuszf** [comment]
Working fine now, thanks !
