### ISSUE TITLE
Move this out of the jQuery org?

### ISSUE THREAD

**Issue by jzaefferer** [JamesMGreene/qunit-composite#13]
Since @JamesMGreene has been maintaing this project for a while anyway, would you be interested in taking it over?

If anyone thinks it should stay here, let us know, too.

**Comment by leobalter** [comment]
I have no objection.

**Comment by jzaefferer** [comment]
@scottgonzalez how can we transfer repos to individuals? I tried in the admin panel, but got this error: "You can only transfer a repository from an organization to yourself at this time".

**Comment by scottgonzalez** [comment]
Create a new team and grant it Owner on this repo, then add @JamesMGreene to the team. He can then perform the transfer and we'll then delete the team.

**Comment by jzaefferer** [comment]
I created the qunit-transfer team, gave it admin access, added James to it and added the team to this repo and the qunit-reporter-junit one. James, you should be to go here: https://github.com/jquery/qunit-reporter-junit/settings and use "Transfer ownership". Same for this repo. Let us know if that works.

**Comment by JamesMGreene** [comment]
OK, I'll try to do so later today when I have a chance to update the URLs in GitHub and NPM, submit PRs for the Plugins page on qunitjs.com, etc.

**Comment by JamesMGreene** [comment]
P.S. @leobalter: Did you have any interest in taking over the qunit-reporter-junit repo?  Just checking before I transfer it.

**Comment by JamesMGreene** [comment]
Moved both out of the jQuery org. Updating their manifests, tagging, publishing, sending PRs for qunitjs.com, etc. now....

**Comment by JamesMGreene** [comment]
All done except for https://github.com/JamesMGreene/qunit-reporter-junit/issues/17.
