### ISSUE TITLE
Update assertion push context for QUnit v1.15.0+

### ISSUE THREAD

**Issue by JamesMGreene** [JamesMGreene/qunit-composite#8]
In QUnit core `v1.15.0`, `QUnit.push` was deprecated in favor of `Assert#push`.  Existing calls to `QUnit.push` in this repo should be updated to something like the following:

```js
( typeof assert.push === "function" ? assert : QUnit ).push( /* ... */ );
```

**Comment by platinumazure** [comment]
With the release of QUnit 2.0, another option is just to break backward compatibility here and do a major version bump.

**Comment by JamesMGreene** [comment]
@platinumazure: Yup, I think that would be ideal.
