### ISSUE TITLE
Remove deprecated asyncTest usage in favor of assert.async for QUnit v1.16.0+

### ISSUE THREAD

**Issue by JamesMGreene** [JamesMGreene/qunit-composite#9]
The forthcoming QUnit `v1.16.0` will deprecate `QUnit.asyncTest` in favor of a new `assert.async()` approach (see jquery/qunit#653).  This plugin should be updated to utilize this style of test as well.

More importantly, this plugin must operate in a very non-standard way that could make it inviable to use the new `assert.async()` approach as a replacement for its current use of `QUnit.stop`/`QUnit.start`. We should confirm that soon-ish as well in case we need to take an alternative approach... most likely we will just need to wrap the `done` callback in an indirect but globally available closure so it can be invoked when the child frame's test run finishes (i.e. as a replacement to [qunit-composite.js#L86-L87](https://github.com/jquery/qunit-composite/blob/92d0dd6022b66814325169ebb01e46726fca7eb4/qunit-composite.js#L86-L87)).

**Comment by platinumazure** [comment]
I might be able to explore this in the next couple of weeks, if you're willing to accept a PR.

**Comment by platinumazure** [comment]
Oh, question. Are you aiming for backward compatible support of pre-1.16, or are you okay with dropping support for that with this change (and possibly doing a major version bump)?

If you did that, you could probably also not bother with the complicated fix to QUnit.push, either.

**Comment by platinumazure** [comment]
Pinging @JamesMGreene. Can you please answer this question when you get a chance?

> Oh, question. Are you aiming for backward compatible support of pre-1.16, or are you okay with dropping support for that with this change (and possibly doing a major version bump)?

Thanks!

**Comment by JamesMGreene** [comment]
Sorry for the [now usual] delay, Kevin.  In all honesty, with the days of QUnit `1.x` coming to an end and QUnit `2.0.0` forthcoming, it's probably best to just hold off on making _any_ change like this until QUnit `2.x` hits the scene.  At that point, we can do a major version bump of this module as well and align it with QUnit `2.x`.

**Comment by platinumazure** [comment]
@JamesMGreene Works for me.

**Comment by jzaefferer** [comment]
You could test against 2.0.0-rc1: https://github.com/jquery/qunit/releases/tag/2.0.0-rc1 - not expecting any relevant changes till the final release.

**Comment by platinumazure** [comment]
@JamesMGreene Now that 2.0.0 is out, should we look into this again? I think the simplest solution is a major version bump of this module and a full breaking change to just go into full QUnit 2.0 compatibility mode.

**Comment by JamesMGreene** [comment]
@platinumazure: Yessir, that would be best.

**Comment by platinumazure** [comment]
Thanks @JamesMGreene. I'll see if I can come up with a PR in the next couple of weeks, unless you beat me to it.
